# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main1006.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1600, 900))
        self.centralwidget.setMaximumSize(QtCore.QSize(1600, 900))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(1600, 900))
        self.frame.setMaximumSize(QtCore.QSize(1600, 900))
        self.frame.setStyleSheet("QFrame{\n"
                                 "    background-color: rgb(255, 255, 255);\n"
                                 "border:0px solid red;\n"
                                 "border-radius:30px\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 265, 900))
        self.frame_3.setMinimumSize(QtCore.QSize(265, 900))
        self.frame_3.setMaximumSize(QtCore.QSize(265, 900))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_12.setSpacing(36)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.widget_7 = QtWidgets.QWidget(self.frame_7)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 32))
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 32))
        self.widget_7.setStyleSheet("image: url(:/svg/Morikawa/01_Data/img/logo/443px.png);")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_17.addWidget(self.widget_7)
        self.verticalLayout_12.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_11.addWidget(self.frame_12)
        self.label_23 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_11.addWidget(self.label_23)
        self.verticalLayout_12.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.listWidget_2 = QtWidgets.QListWidget(self.frame_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.listWidget_2.setFont(font)
        self.listWidget_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.listWidget_2.setStyleSheet("QListView {\n"
                                        "\n"
                                        "}\n"
                                        "QListView::item{\n"
                                        "background-color: transparent;\n"
                                        "    color: rgb(184, 184, 184);\n"
                                        "padding:8px;\n"
                                        "padding-left:4px;\n"
                                        "margin-bottom:8px;\n"
                                        "}\n"
                                        "QListView::item:hover {\n"
                                        "border-radius:8px;\n"
                                        "    background-color: rgb(240, 240, 240)\n"
                                        "\n"
                                        "}\n"
                                        "QListView::item:selected {\n"
                                        "    background-color: rgb(239, 239, 239);\n"
                                        "    color: rgb(12, 20, 36);\n"
                                        "border-radius:8px;\n"
                                        "}\n"
                                        "")
        self.listWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/svg/img/svg/主页.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/svg/img/svg/联系人.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/svg/img/svg/博士帽.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget_2.addItem(item)
        self.horizontalLayout_15.addWidget(self.listWidget_2)
        self.verticalLayout_12.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_16.setContentsMargins(24, 0, -1, 12)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
                                        "    color: rgb(199, 199, 199);\n"
                                        "    border:none;\n"
                                        "    text-align:left;\n"
                                        "    padding:12px;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    border-radius:8px;\n"
                                        "    background-color: rgb(240, 240, 240)\n"
                                        "}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/buttom/img/buttom/退出.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_16.addWidget(self.pushButton_4, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_12.addWidget(self.frame_10)
        self.verticalLayout_12.setStretch(1, 1)
        self.verticalLayout_12.setStretch(2, 2)
        self.verticalLayout_12.setStretch(3, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(277, 0, 1323, 900))
        self.frame_2.setMinimumSize(QtCore.QSize(1323, 900))
        self.frame_2.setMaximumSize(QtCore.QSize(1323, 900))
        self.frame_2.setStyleSheet("QFrame{\n"
                                   "    background-color: rgb(237, 235, 235);\n"
                                   "border:0px solid red;\n"
                                   "border-radius:30px\n"
                                   "}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_13.setContentsMargins(24, 24, 24, 24)
        self.verticalLayout_13.setSpacing(12)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 11, -1)
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("QFrame{\n"
                                   "    background-color: rgb(12, 20, 36);\n"
                                   "border:0px solid red;\n"
                                   "    color: rgb(255, 254, 255);\n"
                                   "border-radius:30px\n"
                                   "}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(18, 18, 18, 24)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777214, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setMinimumSize(QtCore.QSize(0, 52))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 52))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setMinimumSize(QtCore.QSize(0, 52))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 52))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(143, 143, 143);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.frame_4)
        self.line.setMaximumSize(QtCore.QSize(1, 16777215))
        self.line.setStyleSheet("background-color: rgba(255, 255, 255,100);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_6.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setMinimumSize(QtCore.QSize(0, 52))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 52))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setMinimumSize(QtCore.QSize(0, 52))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 52))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(143, 143, 143);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border:none;\n"
                                      "color: rgb(255, 255, 255);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/svg/img/svg/对号1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 32))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border:none;\n"
                                        "color: rgb(255, 255, 255);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/svg/img/svg/对号1 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon5)
        self.pushButton_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 32))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("border:none;\n"
                                        "color: rgb(255, 255, 255);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/svg/img/svg/对号1 (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon6)
        self.pushButton_3.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 32))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 3)
        self.verticalLayout_3.setStretch(2, 3)
        self.verticalLayout_3.setStretch(3, 3)
        self.verticalLayout_3.setStretch(4, 3)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setStyleSheet("QFrame{\n"
                                   "    background-color: rgb(149, 206, 217);\n"
                                   "border:0px solid red;\n"
                                   "    color: rgb(255, 254, 255);\n"
                                   "border-radius:30px\n"
                                   "}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_2)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setStyleSheet("")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_19.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_19.setSpacing(12)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frame_25 = QtWidgets.QFrame(self.frame_6)
        self.frame_25.setStyleSheet("QFrame{\n"
                                    "    background-color: rgb(149, 206, 217);\n"
                                    "border:0px solid red;\n"
                                    "    color: rgb(255, 254, 255);\n"
                                    "border-radius:30px\n"
                                    "}")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.frame_25)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_10.addWidget(self.label_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.frame_25)
        self.label_10.setMinimumSize(QtCore.QSize(0, 52))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.frame_25)
        self.label_11.setMinimumSize(QtCore.QSize(0, 52))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 52))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(143, 143, 143);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.line_2 = QtWidgets.QFrame(self.frame_25)
        self.line_2.setMaximumSize(QtCore.QSize(1, 16777215))
        self.line_2.setStyleSheet("background-color: rgba(255, 255, 255,100);")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_7.addWidget(self.line_2)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_21 = QtWidgets.QLabel(self.frame_25)
        self.label_21.setMinimumSize(QtCore.QSize(0, 52))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_9.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.frame_25)
        self.label_22.setMinimumSize(QtCore.QSize(0, 52))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 52))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(143, 143, 143);")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_9.addWidget(self.label_22)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_19.addWidget(self.frame_25)
        self.frame_11 = QtWidgets.QFrame(self.frame_6)
        self.frame_11.setStyleSheet("QFrame{\n"
                                    "    background-color: rgb(215, 187, 167);\n"
                                    "border:0px solid red;\n"
                                    "    color: rgb(12, 20, 36);\n"
                                    "border-radius:30px\n"
                                    "}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.frame_15 = QtWidgets.QFrame(self.frame_11)
        self.frame_15.setMinimumSize(QtCore.QSize(121, 131))
        self.frame_15.setMaximumSize(QtCore.QSize(121, 131))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.frame_14 = QtWidgets.QFrame(self.frame_15)
        self.frame_14.setGeometry(QtCore.QRect(19, 4, 40, 41))
        self.frame_14.setStyleSheet("\n"
                                    "\n"
                                    "QFrame{\n"
                                    "padding:8px;\n"
                                    "image: url(:/svg/img/svg/闪电-实.png);\n"
                                    "    background-color: rgb(255, 81, 45);\n"
                                    "border:0px solid red;\n"
                                    "border-radius:10px\n"
                                    "}")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.frame_13 = QtWidgets.QFrame(self.frame_15)
        self.frame_13.setGeometry(QtCore.QRect(5, 26, 111, 101))
        self.frame_13.setStyleSheet("QFrame{\n"
                                    "    background-color: rgb(255, 255, 255);\n"
                                    "border:0px solid red;\n"
                                    "border-radius:10px\n"
                                    "}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_5.setContentsMargins(-1, 24, -1, -1)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_14 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_8.addWidget(self.label_14)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.frame_13.raise_()
        self.frame_14.raise_()
        self.horizontalLayout_20.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame_11)
        self.frame_16.setMinimumSize(QtCore.QSize(121, 131))
        self.frame_16.setMaximumSize(QtCore.QSize(121, 131))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.frame_17 = QtWidgets.QFrame(self.frame_16)
        self.frame_17.setGeometry(QtCore.QRect(19, 4, 40, 41))
        self.frame_17.setStyleSheet("\n"
                                    "\n"
                                    "\n"
                                    "\n"
                                    "QFrame{\n"
                                    "padding:8px;\n"
                                    "image: url(:/svg/img/svg/对比.png);\n"
                                    "    background-color: rgb(255, 81, 45);\n"
                                    "border:0px solid red;\n"
                                    "border-radius:10px\n"
                                    "}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.frame_18 = QtWidgets.QFrame(self.frame_16)
        self.frame_18.setGeometry(QtCore.QRect(5, 26, 111, 101))
        self.frame_18.setStyleSheet("QFrame{\n"
                                    "    background-color: rgb(255, 255, 255);\n"
                                    "border:0px solid red;\n"
                                    "border-radius:10px\n"
                                    "}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_6.setContentsMargins(-1, 24, -1, -1)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_15 = QtWidgets.QLabel(self.frame_18)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_16 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        self.widget_2 = QtWidgets.QWidget(self.frame_18)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16))
        self.widget_2.setStyleSheet("image: url(:/buttom/img/buttom/下-小_down-small.svg);")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_9.addWidget(self.widget_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.frame_18.raise_()
        self.frame_17.raise_()
        self.horizontalLayout_20.addWidget(self.frame_16)
        self.frame_19 = QtWidgets.QFrame(self.frame_11)
        self.frame_19.setMinimumSize(QtCore.QSize(121, 131))
        self.frame_19.setMaximumSize(QtCore.QSize(121, 131))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.frame_20 = QtWidgets.QFrame(self.frame_19)
        self.frame_20.setGeometry(QtCore.QRect(19, 4, 40, 41))
        self.frame_20.setStyleSheet("\n"
                                    "\n"
                                    "\n"
                                    "\n"
                                    "\n"
                                    "QFrame{\n"
                                    "padding:8px;\n"
                                    "image: url(:/svg/img/svg/星星.png);\n"
                                    "\n"
                                    "    background-color: rgb(255, 81, 45);\n"
                                    "border:0px solid red;\n"
                                    "border-radius:10px\n"
                                    "}")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.frame_21 = QtWidgets.QFrame(self.frame_19)
        self.frame_21.setGeometry(QtCore.QRect(5, 26, 111, 101))
        self.frame_21.setStyleSheet("QFrame{\n"
                                    "    background-color: rgb(255, 255, 255);\n"
                                    "border:0px solid red;\n"
                                    "border-radius:10px\n"
                                    "}")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_7.setContentsMargins(-1, 24, -1, -1)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_17 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_7.addWidget(self.label_17)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_18 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_10.addWidget(self.label_18)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.frame_21.raise_()
        self.frame_20.raise_()
        self.horizontalLayout_20.addWidget(self.frame_19)
        self.frame_22 = QtWidgets.QFrame(self.frame_11)
        self.frame_22.setMinimumSize(QtCore.QSize(121, 131))
        self.frame_22.setMaximumSize(QtCore.QSize(121, 131))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.frame_23 = QtWidgets.QFrame(self.frame_22)
        self.frame_23.setGeometry(QtCore.QRect(19, 4, 40, 41))
        self.frame_23.setStyleSheet("\n"
                                    "\n"
                                    "\n"
                                    "\n"
                                    "\n"
                                    "\n"
                                    "QFrame{\n"
                                    "padding:8px;\n"
                                    "image: url(:/svg/img/svg/光照强度.png);\n"
                                    "    background-color: rgb(255, 81, 45);\n"
                                    "border:0px solid red;\n"
                                    "border-radius:10px\n"
                                    "}")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.frame_24 = QtWidgets.QFrame(self.frame_22)
        self.frame_24.setGeometry(QtCore.QRect(5, 26, 111, 101))
        self.frame_24.setStyleSheet("QFrame{\n"
                                    "    background-color: rgb(255, 255, 255);\n"
                                    "border:0px solid red;\n"
                                    "border-radius:10px\n"
                                    "}")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_8.setContentsMargins(-1, 24, -1, -1)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_19 = QtWidgets.QLabel(self.frame_24)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_8.addWidget(self.label_19)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_20 = QtWidgets.QLabel(self.frame_24)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_11.addWidget(self.label_20)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.frame_24.raise_()
        self.frame_23.raise_()
        self.horizontalLayout_20.addWidget(self.frame_22)
        self.frame_27 = QtWidgets.QFrame(self.frame_11)
        self.frame_27.setMinimumSize(QtCore.QSize(121, 131))
        self.frame_27.setMaximumSize(QtCore.QSize(121, 131))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.frame_28 = QtWidgets.QFrame(self.frame_27)
        self.frame_28.setGeometry(QtCore.QRect(19, 4, 40, 41))
        self.frame_28.setStyleSheet("\n"
                                    "\n"
                                    "\n"
                                    "\n"
                                    "\n"
                                    "\n"
                                    "QFrame{\n"
                                    "padding:8px;\n"
                                    "image: url(:/svg/img/svg/tvoc.png);\n"
                                    "    background-color: rgb(255, 81, 45);\n"
                                    "border:0px solid red;\n"
                                    "border-radius:10px\n"
                                    "}")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.frame_29 = QtWidgets.QFrame(self.frame_27)
        self.frame_29.setGeometry(QtCore.QRect(5, 26, 111, 101))
        self.frame_29.setStyleSheet("QFrame{\n"
                                    "    background-color: rgb(255, 255, 255);\n"
                                    "border:0px solid red;\n"
                                    "border-radius:10px\n"
                                    "}")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_15.setContentsMargins(-1, 24, -1, -1)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_26 = QtWidgets.QLabel(self.frame_29)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_15.addWidget(self.label_26)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_27 = QtWidgets.QLabel(self.frame_29)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_13.addWidget(self.label_27)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.frame_29.raise_()
        self.frame_28.raise_()
        self.horizontalLayout_20.addWidget(self.frame_27)
        self.frame_30 = QtWidgets.QFrame(self.frame_11)
        self.frame_30.setMinimumSize(QtCore.QSize(121, 131))
        self.frame_30.setMaximumSize(QtCore.QSize(121, 131))
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.frame_31 = QtWidgets.QFrame(self.frame_30)
        self.frame_31.setGeometry(QtCore.QRect(19, 4, 40, 41))
        self.frame_31.setStyleSheet("\n"
                                    "\n"
                                    "\n"
                                    "\n"
                                    "\n"
                                    "\n"
                                    "QFrame{\n"
                                    "padding:8px;\n"
                                    "image: url(:/svg/img/svg/co2.png);\n"
                                    "    background-color: rgb(255, 81, 45);\n"
                                    "border:0px solid red;\n"
                                    "border-radius:10px\n"
                                    "}")
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.frame_32 = QtWidgets.QFrame(self.frame_30)
        self.frame_32.setGeometry(QtCore.QRect(5, 26, 111, 101))
        self.frame_32.setStyleSheet("QFrame{\n"
                                    "    background-color: rgb(255, 255, 255);\n"
                                    "border:0px solid red;\n"
                                    "border-radius:10px\n"
                                    "}")
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_32)
        self.verticalLayout_16.setContentsMargins(-1, 24, -1, -1)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_28 = QtWidgets.QLabel(self.frame_32)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_16.addWidget(self.label_28)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_29 = QtWidgets.QLabel(self.frame_32)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_18.addWidget(self.label_29)
        self.verticalLayout_16.addLayout(self.horizontalLayout_18)
        self.frame_32.raise_()
        self.frame_31.raise_()
        self.horizontalLayout_20.addWidget(self.frame_30)
        self.horizontalLayout_19.addWidget(self.frame_11)
        self.horizontalLayout_19.setStretch(0, 1)
        self.horizontalLayout_19.setStretch(1, 3)
        self.verticalLayout_13.addWidget(self.frame_6)
        self.verticalLayout_13.setStretch(0, 3)
        self.verticalLayout_13.setStretch(1, 1)
        self.frame_26 = QtWidgets.QFrame(self.frame)
        self.frame_26.setGeometry(QtCore.QRect(277, 0, 1323, 900))
        self.frame_26.setMinimumSize(QtCore.QSize(1323, 900))
        self.frame_26.setMaximumSize(QtCore.QSize(1323, 900))
        self.frame_26.setStyleSheet("QFrame{\n"
                                    "    background-color: rgb(237, 235, 235);\n"
                                    "    border:0px solid red;\n"
                                    "    border-radius:30px\n"
                                    "}")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_12 = QtWidgets.QLabel(self.frame_26)
        self.label_12.setStyleSheet("")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_14.addWidget(self.label_12)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_24 = QtWidgets.QLabel(self.frame_26)
        self.label_24.setMinimumSize(QtCore.QSize(1000, 0))
        self.label_24.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_12.addWidget(self.label_24)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_26)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_5.setMaximumSize(QtCore.QSize(100, 40))
        self.pushButton_5.setStyleSheet("QPushButton\n"
                                        "{\n"
                                        "    font-family:Microsoft Yahei;\n"
                                        "    font:20px;\n"
                                        "    color:white;\n"
                                        "    background-color:rgb(14 , 150 , 254);\n"
                                        "    border-radius:15px;\n"
                                        "    height:50px;\n"
                                        "    width:200px;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover\n"
                                        "{\n"
                                        "    background-color:rgb(44 , 137 , 255);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed\n"
                                        "{\n"
                                        "    background-color:rgb(14 , 135 , 228);\n"
                                        "    padding-left:3px;\n"
                                        "    padding-top:3px;\n"
                                        "}\n"
                                        "")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_12.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_26)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_6.setMaximumSize(QtCore.QSize(100, 40))
        self.pushButton_6.setStyleSheet("QPushButton\n"
                                        "{\n"
                                        "    font-family:Microsoft Yahei;\n"
                                        "    font:20px;\n"
                                        "    color:white;\n"
                                        "    background-color:rgb(14 , 150 , 254);\n"
                                        "    border-radius:15px;\n"
                                        "    height:50px;\n"
                                        "    width:200px;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover\n"
                                        "{\n"
                                        "    background-color:rgb(44 , 137 , 255);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed\n"
                                        "{\n"
                                        "    background-color:rgb(14 , 135 , 228);\n"
                                        "    padding-left:3px;\n"
                                        "    padding-top:3px;\n"
                                        "}\n"
                                        "")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_12.addWidget(self.pushButton_6)
        self.horizontalLayout_12.setStretch(0, 2)
        self.horizontalLayout_12.setStretch(1, 1)
        self.horizontalLayout_12.setStretch(2, 1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_12)
        self.label_25 = QtWidgets.QLabel(self.frame_26)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("padding-left:30px;")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_14.addWidget(self.label_25)
        self.verticalLayout_14.setStretch(0, 6)
        self.verticalLayout_14.setStretch(1, 1)
        self.verticalLayout_14.setStretch(2, 1)
        self.frame_26.raise_()
        self.frame_3.raise_()
        self.frame_2.raise_()
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.listWidget_2.setCurrentRow(-1)
        self.pushButton_4.clicked.connect(MainWindow.close)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_23.setText(_translate("MainWindow", "智慧农业系统"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "主页"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "天气预报"))
        item = self.listWidget_2.item(2)
        item.setText(_translate("MainWindow", "病虫害检测"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.pushButton_4.setText(_translate("MainWindow", "Exit"))
        self.label.setText(_translate("MainWindow", "状态检测器"))
        self.label_2.setText(_translate("MainWindow", "210.9g"))
        self.label_4.setText(_translate("MainWindow", "种仓空间"))
        self.label_3.setText(_translate("MainWindow", "0%"))
        self.label_5.setText(_translate("MainWindow", "土壤湿度"))
        self.pushButton.setText(_translate("MainWindow", "当前土壤较湿润"))
        self.label_6.setText(_translate("MainWindow", "适宜播种"))
        self.pushButton_2.setText(_translate("MainWindow", "种仓空间充足"))
        self.label_7.setText(_translate("MainWindow", "无需添种"))
        self.pushButton_3.setText(_translate("MainWindow", "当前天气多云"))
        self.label_8.setText(_translate("MainWindow", "适宜播种"))
        self.label_9.setText(_translate("MainWindow", "当前工作模式"))
        self.label_10.setText(_translate("MainWindow", "手动操控"))
        self.label_11.setText(_translate("MainWindow", "驱动模式"))
        self.label_21.setText(_translate("MainWindow", "手动播种"))
        self.label_22.setText(_translate("MainWindow", "播种方式"))
        self.label_13.setText(_translate("MainWindow", "电池电量"))
        self.label_14.setText(_translate("MainWindow", "90%"))
        self.label_15.setText(_translate("MainWindow", "空气温度"))
        self.label_16.setText(_translate("MainWindow", "28℃"))
        self.label_17.setText(_translate("MainWindow", "空气湿度"))
        self.label_18.setText(_translate("MainWindow", "78.1%"))
        self.label_19.setText(_translate("MainWindow", "光照强度"))
        self.label_20.setText(_translate("MainWindow", "400lx"))
        self.label_26.setText(_translate("MainWindow", "TVOC(ppb)"))
        self.label_27.setText(_translate("MainWindow", "0"))
        self.label_28.setText(_translate("MainWindow", "CO2(ppm)"))
        self.label_29.setText(_translate("MainWindow", "0"))
        self.label_24.setText(_translate("MainWindow", "检测结果："))
        self.pushButton_5.setText(_translate("MainWindow", "拍摄"))
        self.pushButton_6.setText(_translate("MainWindow", "检测"))


import resources_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
